apiVersion: apps/v1
kind: Deployment
metadata:
  name: melpominee-bot
  namespace: melpominee
  labels:
    app: melpominee-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: melpominee-bot
  template:
    metadata:
      labels:
        app: melpominee-bot
    spec:
      volumes:
      - name: config-volume
        projected:
          sources:
          - secret:
              name: melpominee-discord
      containers:
      - name: bot
        image: ghcr.io/imsilvz/melpominee-bot:master
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
        volumeMounts:
        - name: config-volume
          mountPath: "/app/secrets"
          readOnly: true
      imagePullSecrets:
      - name: dockerconfigjson-github-com