apiVersion: apps/v1
kind: Deployment
metadata:
  name: melpominee-bot
  namespace: melpominee
  labels:
    app: melpominee-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: melpominee-bot
  template:
    metadata:
      labels:
        app: melpominee-bot
    spec:
      containers:
      - name: bot
        image: ghcr.io/imsilvz/melpominee-bot:master
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      imagePullSecrets:
      - name: dockerconfigjson-github-com