name: Melpominee Bot Deployment
on:
  push:
    branches:
      - master 
  schedule:
    - cron: '0 10 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  actions: read
  contents: read
  packages: write
  id-token: write

jobs:
  docker-build-push:
    name: Melpominee Bot Build & Push
    runs-on: melpominee-bot-runner
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build & Push Container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/setup-kubectl@v4
        id: install

      - name: Gets K8s context
        uses: azure/aks-set-context@v4
        with:
            resource-group: ${{ vars.AZURE_GROUP }}
            cluster-name: ${{ vars.AZURE_CLUSTER }}
        id: login

      - name: Deploy Manifests
        uses: Azure/k8s-deploy@v5
        with:
          action: 'deploy'
          manifests: |
            manifests/bot.yaml
          namespace: 'melpominee'

      - name: Issue Restart
        run: |
          kubectl rollout restart deployment melpominee-bot --namespace=melpominee